/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type {
  BamlRuntime,
  BamlCtxManager,
  ClientRegistry,
  Image,
  Audio,
  Pdf,
  Video,
  Collector,
} from '@boundaryml/baml';
import { toBamlError } from '@boundaryml/baml';
import type { Checked, Check } from './types';
import type { partial_types } from './partial_types';
import type * as types from './types';
import type {
  AgentDecision,
  AgentState,
  CriteriaScore,
  Decision,
  DocumentEvaluation,
  DocumentToRerank,
  Entity,
  EssayGrade,
  EssaySubmission,
  Explanation,
  GradingCriteria,
  GrammarCorrection,
  HyDE_query,
  HyDE_rewrite_query,
  KnowledgePoints,
  Knowledge_extraction_tool,
  Message,
  MutatedQuiz,
  Option,
  Quiz_retrieval_tool,
  Rawquiz_A,
  Related_documents,
  RelationshipSummary,
  RetrievedDocument,
  StepResponse,
  StructureAnalysis,
  Task,
  Textbook_semantic_search_tool,
  ToolCall,
  ToolDefinition,
  ToolList,
  ToolParameter,
  ToolResult,
  TranslationCorrection,
  VocabularySuggestion,
} from './types';
import type TypeBuilder from './type_builder';

export class LlmResponseParser {
  constructor(
    private runtime: BamlRuntime,
    private ctxManager: BamlCtxManager,
  ) {}

  AgentDecideNextAction(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): types.AgentDecision {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'AgentDecideNextAction',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as types.AgentDecision;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnnotateClass(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): '生理学' | '病理学' | '生物化学' | '内科学' | '外科学' {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'AnnotateClass',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as '生理学' | '病理学' | '生物化学' | '内科学' | '外科学';
    } catch (error) {
      throw toBamlError(error);
    }
  }

  CorrectTranslation(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): types.TranslationCorrection {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'CorrectTranslation',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as types.TranslationCorrection;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  EvaluateDocumentSufficiency(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): types.DocumentEvaluation {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'EvaluateDocumentSufficiency',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as types.DocumentEvaluation;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  ExecuteToolCall(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): types.ToolResult {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'ExecuteToolCall',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as types.ToolResult;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  ExtractMainEntity(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): types.Entity[] {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'ExtractMainEntity',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as types.Entity[];
    } catch (error) {
      throw toBamlError(error);
    }
  }

  Extract_related_documents(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): types.Related_documents {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'Extract_related_documents',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as types.Related_documents;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  FilterRelatedChunks(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): number[] {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'FilterRelatedChunks',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as number[];
    } catch (error) {
      throw toBamlError(error);
    }
  }

  FinalizeAgentResponse(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): types.StepResponse {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'FinalizeAgentResponse',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as types.StepResponse;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GenerateAgentResponse(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): types.StepResponse {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'GenerateAgentResponse',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as types.StepResponse;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GenerateAnswer(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): string {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'GenerateAnswer',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as string;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GenerateAntiMemorizationQuiz(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): types.MutatedQuiz {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'GenerateAntiMemorizationQuiz',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as types.MutatedQuiz;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GenerateExplanation(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): types.Explanation {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'GenerateExplanation',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as types.Explanation;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GenerateExplanationForAnalysis(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): types.Explanation {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'GenerateExplanationForAnalysis',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as types.Explanation;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GenerateQuizQuery(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): types.HyDE_query[] {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'GenerateQuizQuery',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as types.HyDE_query[];
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GenerateQuizVarient(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): types.MutatedQuiz {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'GenerateQuizVarient',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as types.MutatedQuiz;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GenerateQuizzes_single(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): types.Rawquiz_A[] {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'GenerateQuizzes_single',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as types.Rawquiz_A[];
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GetGradingCriteriaSet(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): types.GradingCriteria[] {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'GetGradingCriteriaSet',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as types.GradingCriteria[];
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GradeEssayImage(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): types.EssayGrade {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'GradeEssayImage',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as types.EssayGrade;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GradeEssayText(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): types.EssayGrade {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'GradeEssayText',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as types.EssayGrade;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  HyDE_rewrite(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): types.HyDE_rewrite_query {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'HyDE_rewrite',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as types.HyDE_rewrite_query;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  HyDE_rewriteForAnalysis(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): types.HyDE_rewrite_query {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'HyDE_rewriteForAnalysis',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as types.HyDE_rewrite_query;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  PlanNextStep(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): types.Decision {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'PlanNextStep',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as types.Decision;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  RerankDocuments(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): number[] {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'RerankDocuments',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as number[];
    } catch (error) {
      throw toBamlError(error);
    }
  }

  SummarizeKnowledgePoint(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): types.KnowledgePoints[] {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'SummarizeKnowledgePoint',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as types.KnowledgePoints[];
    } catch (error) {
      throw toBamlError(error);
    }
  }

  SummarizeKnowledgePointForAnalysis(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): types.KnowledgePoints[] {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'SummarizeKnowledgePointForAnalysis',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as types.KnowledgePoints[];
    } catch (error) {
      throw toBamlError(error);
    }
  }

  SummarizeRelationships(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): types.RelationshipSummary {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'SummarizeRelationships',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as types.RelationshipSummary;
    } catch (error) {
      throw toBamlError(error);
    }
  }
}

export class LlmStreamParser {
  constructor(
    private runtime: BamlRuntime,
    private ctxManager: BamlCtxManager,
  ) {}

  AgentDecideNextAction(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): partial_types.AgentDecision {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'AgentDecideNextAction',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as partial_types.AgentDecision;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnnotateClass(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): '生理学' | '病理学' | '生物化学' | '内科学' | '外科学' {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'AnnotateClass',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as '生理学' | '病理学' | '生物化学' | '内科学' | '外科学';
    } catch (error) {
      throw toBamlError(error);
    }
  }

  CorrectTranslation(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): partial_types.TranslationCorrection {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'CorrectTranslation',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as partial_types.TranslationCorrection;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  EvaluateDocumentSufficiency(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): partial_types.DocumentEvaluation {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'EvaluateDocumentSufficiency',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as partial_types.DocumentEvaluation;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  ExecuteToolCall(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): partial_types.ToolResult {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'ExecuteToolCall',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as partial_types.ToolResult;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  ExtractMainEntity(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): partial_types.Entity[] {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'ExtractMainEntity',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as partial_types.Entity[];
    } catch (error) {
      throw toBamlError(error);
    }
  }

  Extract_related_documents(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): partial_types.Related_documents {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'Extract_related_documents',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as partial_types.Related_documents;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  FilterRelatedChunks(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): number[] {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'FilterRelatedChunks',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as number[];
    } catch (error) {
      throw toBamlError(error);
    }
  }

  FinalizeAgentResponse(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): partial_types.StepResponse {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'FinalizeAgentResponse',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as partial_types.StepResponse;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GenerateAgentResponse(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): partial_types.StepResponse {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'GenerateAgentResponse',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as partial_types.StepResponse;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GenerateAnswer(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): string {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'GenerateAnswer',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as string;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GenerateAntiMemorizationQuiz(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): partial_types.MutatedQuiz {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'GenerateAntiMemorizationQuiz',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as partial_types.MutatedQuiz;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GenerateExplanation(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): partial_types.Explanation {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'GenerateExplanation',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as partial_types.Explanation;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GenerateExplanationForAnalysis(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): partial_types.Explanation {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'GenerateExplanationForAnalysis',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as partial_types.Explanation;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GenerateQuizQuery(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): partial_types.HyDE_query[] {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'GenerateQuizQuery',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as partial_types.HyDE_query[];
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GenerateQuizVarient(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): partial_types.MutatedQuiz {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'GenerateQuizVarient',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as partial_types.MutatedQuiz;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GenerateQuizzes_single(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): partial_types.Rawquiz_A[] {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'GenerateQuizzes_single',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as partial_types.Rawquiz_A[];
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GetGradingCriteriaSet(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): partial_types.GradingCriteria[] {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'GetGradingCriteriaSet',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as partial_types.GradingCriteria[];
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GradeEssayImage(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): partial_types.EssayGrade {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'GradeEssayImage',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as partial_types.EssayGrade;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GradeEssayText(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): partial_types.EssayGrade {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'GradeEssayText',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as partial_types.EssayGrade;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  HyDE_rewrite(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): partial_types.HyDE_rewrite_query {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'HyDE_rewrite',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as partial_types.HyDE_rewrite_query;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  HyDE_rewriteForAnalysis(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): partial_types.HyDE_rewrite_query {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'HyDE_rewriteForAnalysis',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as partial_types.HyDE_rewrite_query;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  PlanNextStep(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): partial_types.Decision {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'PlanNextStep',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as partial_types.Decision;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  RerankDocuments(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): number[] {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'RerankDocuments',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as number[];
    } catch (error) {
      throw toBamlError(error);
    }
  }

  SummarizeKnowledgePoint(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): partial_types.KnowledgePoints[] {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'SummarizeKnowledgePoint',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as partial_types.KnowledgePoints[];
    } catch (error) {
      throw toBamlError(error);
    }
  }

  SummarizeKnowledgePointForAnalysis(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): partial_types.KnowledgePoints[] {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'SummarizeKnowledgePointForAnalysis',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as partial_types.KnowledgePoints[];
    } catch (error) {
      throw toBamlError(error);
    }
  }

  SummarizeRelationships(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): partial_types.RelationshipSummary {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        'SummarizeRelationships',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as partial_types.RelationshipSummary;
    } catch (error) {
      throw toBamlError(error);
    }
  }
}
