/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export enum AdministrationRoute {
  Oral = "Oral",
  Intravenous = "Intravenous",
  Intramuscular = "Intramuscular",
  Subcutaneous = "Subcutaneous",
  Topical = "Topical",
  Inhaled = "Inhaled",
  Other = "Other",
}

export enum AgeGroup {
  Children = "Children",
  Adults = "Adults",
  Elderly = "Elderly",
  NotSpecified = "NotSpecified",
}

export enum AllocationConcealment {
  Adequate = "Adequate",
  Unclear = "Unclear",
  NotRequired = "NotRequired",
}

/**
 * Article types for filtering
 */
export enum ArticleType {
  ClinicalTrial = "ClinicalTrial",
  ClinicalTrialPhaseI = "ClinicalTrialPhaseI",
  ClinicalTrialPhaseII = "ClinicalTrialPhaseII",
  ClinicalTrialPhaseIII = "ClinicalTrialPhaseIII",
  ClinicalTrialPhaseIV = "ClinicalTrialPhaseIV",
  ControlledClinicalTrial = "ControlledClinicalTrial",
  RandomizedControlledTrial = "RandomizedControlledTrial",
  MetaAnalysis = "MetaAnalysis",
  SystematicReview = "SystematicReview",
  ObservationalStudy = "ObservationalStudy",
  CaseReport = "CaseReport",
  CaseSeries = "CaseSeries",
  CohortStudy = "CohortStudy",
  CrossSectionalStudy = "CrossSectionalStudy",
  CaseControlStudy = "CaseControlStudy",
  Editorial = "Editorial",
  Letter = "Letter",
  Review = "Review",
  Guideline = "Guideline",
}

export enum BiasAssessmentTool {
  CochraneRoB2 = "CochraneRoB2",
  ROBINSI = "ROBINSI",
  NOS = "NOS",
  Jadad = "Jadad",
  NotSpecified = "NotSpecified",
}

export enum BiasRiskLevel {
  LowRiskOnly = "LowRiskOnly",
  LowAndMediumRisk = "LowAndMediumRisk",
  AnyRisk = "AnyRisk",
}

export enum BlindingType {
  DoubleBlind = "DoubleBlind",
  SingleBlindParticipant = "SingleBlindParticipant",
  SingleBlindInvestigator = "SingleBlindInvestigator",
  TripleBlind = "TripleBlind",
  OpenLabel = "OpenLabel",
  NotSpecified = "NotSpecified",
}

export enum CombinationIntervention {
  SingleIntervention = "SingleIntervention",
  AllowsBackgroundTherapy = "AllowsBackgroundTherapy",
  AllowsSpecificCombination = "AllowsSpecificCombination",
  ExcludesCombination = "ExcludesCombination",
}

export enum ComparisonDoseType {
  StandardRecommended = "StandardRecommended",
  FixedDose = "FixedDose",
  AdjustableDose = "AdjustableDose",
  NotSpecified = "NotSpecified",
}

export enum ComparisonSpecificity {
  SpecificComparator = "SpecificComparator",
  SameClassComparator = "SameClassComparator",
  AnyComparator = "AnyComparator",
}

export enum ComparisonType {
  Placebo = "Placebo",
  ActiveControl = "ActiveControl",
  StandardTreatment = "StandardTreatment",
  Waitlist = "Waitlist",
  NoTreatment = "NoTreatment",
  HistoricalControl = "HistoricalControl",
  SelfControl = "SelfControl",
}

export enum ComplianceStandard {
  CONSORT = "CONSORT",
  STROBE = "STROBE",
  PRISMA = "PRISMA",
  NotSpecified = "NotSpecified",
}

export enum ConflictOfInterest {
  Reported = "Reported",
  None = "None",
}

export enum CountryIncomeLevel {
  HighIncome = "HighIncome",
  MiddleIncome = "MiddleIncome",
  LowIncome = "LowIncome",
}

export enum CriteriaType {
  Inclusion = "Inclusion",
  Exclusion = "Exclusion",
}

export enum DataFormat {
  MeanSD = "MeanSD",
  MedianIQR = "MedianIQR",
  MeanCI = "MeanCI",
  EventCount = "EventCount",
  EffectSizeCI = "EffectSizeCI",
  Other = "Other",
}

/**
 * Supported databases
 */
export enum Database {
  PubMed = "PubMed",
  Embase = "Embase",
  WebOfScience = "WebOfScience",
  Scopus = "Scopus",
  Cochrane = "Cochrane",
  CINAHL = "CINAHL",
  PsycINFO = "PsycINFO",
}

export enum DiseaseActivity {
  Active = "Active",
  Remission = "Remission",
  Stable = "Stable",
  NotSpecified = "NotSpecified",
}

export enum DiseaseCourse {
  NewlyDiagnosed = "NewlyDiagnosed",
  ShortDuration = "ShortDuration",
  LongDuration = "LongDuration",
  Chronic = "Chronic",
  NotSpecified = "NotSpecified",
}

export enum DoseType {
  FixedDose = "FixedDose",
  AdjustableDose = "AdjustableDose",
  TitratedDose = "TitratedDose",
  NotSpecified = "NotSpecified",
}

export enum ExposureDuration {
  Acute = "Acute",
  Chronic = "Chronic",
  SpecificDuration = "SpecificDuration",
  NotSpecified = "NotSpecified",
}

export enum ExposureIntensity {
  High = "High",
  Low = "Low",
  Graded = "Graded",
  NotSpecified = "NotSpecified",
}

export enum ExposureType {
  Environmental = "Environmental",
  Occupational = "Occupational",
  Lifestyle = "Lifestyle",
  Genetic = "Genetic",
  Biomarker = "Biomarker",
}

export enum FollowUpDuration {
  ShortTerm = "ShortTerm",
  MediumTerm = "MediumTerm",
  LongTerm = "LongTerm",
  NotSpecified = "NotSpecified",
}

export enum FollowUpTime {
  ShortTerm = "ShortTerm",
  MediumTerm = "MediumTerm",
  LongTerm = "LongTerm",
  NotSpecified = "NotSpecified",
}

export enum FundingSource {
  NonProfitOnly = "NonProfitOnly",
  IncludesIndustry = "IncludesIndustry",
}

export enum GenderRequirement {
  MaleOnly = "MaleOnly",
  FemaleOnly = "FemaleOnly",
  BothRequired = "BothRequired",
  NotSpecified = "NotSpecified",
}

export enum GreyLiterature {
  IncludeGreyLiterature = "IncludeGreyLiterature",
  PublishedOnly = "PublishedOnly",
}

export enum HospitalLevel {
  Tertiary = "Tertiary",
  Secondary = "Secondary",
  Community = "Community",
  NotSpecified = "NotSpecified",
}

export enum InterventionCategory {
  Pharmacological = "Pharmacological",
  Surgical = "Surgical",
  PhysicalTherapy = "PhysicalTherapy",
  Psychological = "Psychological",
  Lifestyle = "Lifestyle",
  Rehabilitation = "Rehabilitation",
  Educational = "Educational",
  Nutritional = "Nutritional",
  Device = "Device",
  Other = "Other",
}

/**
 * Language filters
 */
export enum Language {
  English = "English",
  Chinese = "Chinese",
  French = "French",
  German = "German",
  Spanish = "Spanish",
  Japanese = "Japanese",
  Any = "Any",
}

/**
 * Logical operator between concepts
 */
export enum LogicalOperator {
  AND = "AND",
  OR = "OR",
  NOT = "NOT",
}

export enum MeasurementMethod {
  StandardizedScale = "StandardizedScale",
  ObjectiveMeasurement = "ObjectiveMeasurement",
  Imaging = "Imaging",
  Questionnaire = "Questionnaire",
  NotSpecified = "NotSpecified",
}

export enum MedicalSetting {
  Inpatient = "Inpatient",
  Outpatient = "Outpatient",
  Community = "Community",
  NotSpecified = "NotSpecified",
}

export enum ObservationalStudyType {
  ProspectiveOnly = "ProspectiveOnly",
  RetrospectiveOnly = "RetrospectiveOnly",
  BothAccepted = "BothAccepted",
}

export enum OutcomeAssessorBlinding {
  Blinded = "Blinded",
  NotRequired = "NotRequired",
}

export enum OutcomeCategory {
  Primary = "Primary",
  Secondary = "Secondary",
  Exploratory = "Exploratory",
}

export enum OutcomeDataType {
  Continuous = "Continuous",
  Binary = "Binary",
  Ordinal = "Ordinal",
  TimeToEvent = "TimeToEvent",
  Count = "Count",
}

export enum OutcomeNature {
  Efficacy = "Efficacy",
  Safety = "Safety",
  Survival = "Survival",
  QualityOfLife = "QualityOfLife",
  Economic = "Economic",
  Biomarker = "Biomarker",
}

export enum PeerReviewStatus {
  PeerReviewed = "PeerReviewed",
  NonPeerReviewed = "NonPeerReviewed",
}

/**
 * Age groups for filtering (PubMed-specific)
 */
export enum PubMedAgeGroup {
  Newborn = "Newborn",
  Infant = "Infant",
  Preschool = "Preschool",
  Child = "Child",
  Adolescent = "Adolescent",
  Adult = "Adult",
  MiddleAged = "MiddleAged",
  Aged = "Aged",
  Aged80Plus = "Aged80Plus",
}

export enum PubMedField {
  AllFields = "AllFields",
  Affiliation = "Affiliation",
  Author = "Author",
  AuthorCorporate = "AuthorCorporate",
  AuthorFirst = "AuthorFirst",
  AuthorIdentifier = "AuthorIdentifier",
  AuthorLast = "AuthorLast",
  Book = "Book",
  ConflictOfInterestStatements = "ConflictOfInterestStatements",
  DateCompletion = "DateCompletion",
  DateCreate = "DateCreate",
  DateEntry = "DateEntry",
  DateMeSH = "DateMeSH",
  DateModification = "DateModification",
  DatePublication = "DatePublication",
  ECRNNumber = "ECRNNumber",
  Editor = "Editor",
  Filter = "Filter",
  GrantsAndFunding = "GrantsAndFunding",
  ISBN = "ISBN",
  Investigator = "Investigator",
  Issue = "Issue",
  Journal = "Journal",
  Language = "Language",
  LocationID = "LocationID",
  MeSHMajorTopic = "MeSHMajorTopic",
  MeSHSubheading = "MeSHSubheading",
  MeSHTerms = "MeSHTerms",
  OtherTerm = "OtherTerm",
  Pagination = "Pagination",
  PharmacologicalAction = "PharmacologicalAction",
  PublicationType = "PublicationType",
  Publisher = "Publisher",
  SecondarySourceID = "SecondarySourceID",
  SubjectPersonalName = "SubjectPersonalName",
  SupplementaryConcept = "SupplementaryConcept",
  TextWord = "TextWord",
  Title = "Title",
  TitleAbstract = "TitleAbstract",
  TransliteratedTitle = "TransliteratedTitle",
  Volume = "Volume",
}

export enum PublicationLanguage {
  EnglishOnly = "EnglishOnly",
  EnglishAndChinese = "EnglishAndChinese",
  AnyLanguage = "AnyLanguage",
  SpecificLanguages = "SpecificLanguages",
}

export enum PublicationType {
  FullText = "FullText",
  ConferenceAbstract = "ConferenceAbstract",
  Dissertation = "Dissertation",
  Preprint = "Preprint",
}

export enum RCTDesignType {
  Parallel = "Parallel",
  Crossover = "Crossover",
  Factorial = "Factorial",
  ClusterRandomized = "ClusterRandomized",
  NonInferiority = "NonInferiority",
  Superiority = "Superiority",
  Equivalence = "Equivalence",
}

export enum RandomizationMethod {
  AdequateRandomization = "AdequateRandomization",
  SimpleRandomization = "SimpleRandomization",
  StratifiedRandomization = "StratifiedRandomization",
  BlockRandomization = "BlockRandomization",
  NotSpecified = "NotSpecified",
}

/**
 * Sex for filtering
 */
export enum Sex {
  Male = "Male",
  Female = "Female",
}

export enum SpecialPopulation {
  Pregnant = "Pregnant",
  Lactating = "Lactating",
  Pediatric = "Pediatric",
  Geriatric = "Geriatric",
  ICU = "ICU",
  Immunocompromised = "Immunocompromised",
  None = "None",
}

/**
 * Species for filtering
 */
export enum Species {
  Humans = "Humans",
  Animals = "Animals",
}

export enum StatisticalAnalysis {
  AppropriateMethods = "AppropriateMethods",
  AdjustsConfounders = "AdjustsConfounders",
  IntentionToTreat = "IntentionToTreat",
  PerProtocol = "PerProtocol",
  NotSpecified = "NotSpecified",
}

export enum StudyDesignType {
  RCT = "RCT",
  CohortStudy = "CohortStudy",
  CaseControlStudy = "CaseControlStudy",
  CrossSectionalStudy = "CrossSectionalStudy",
  CaseSeries = "CaseSeries",
  CaseReport = "CaseReport",
  DiagnosticAccuracyStudy = "DiagnosticAccuracyStudy",
  PrognosticStudy = "PrognosticStudy",
  MixedStudy = "MixedStudy",
}

export enum StudyNature {
  Exploratory = "Exploratory",
  Confirmatory = "Confirmatory",
  BothAccepted = "BothAccepted",
}

export enum StudyScale {
  SingleCenter = "SingleCenter",
  MultiCenter = "MultiCenter",
  International = "International",
}

export enum TreatmentFrequency {
  SingleDose = "SingleDose",
  Daily = "Daily",
  Weekly = "Weekly",
  Monthly = "Monthly",
  AsNeeded = "AsNeeded",
  NotSpecified = "NotSpecified",
}

export enum TreatmentHistory {
  TreatmentNaive = "TreatmentNaive",
  TreatmentExperienced = "TreatmentExperienced",
  TreatmentFailed = "TreatmentFailed",
  StableTreatment = "StableTreatment",
  NotSpecified = "NotSpecified",
}

export enum TreatmentTiming {
  Preoperative = "Preoperative",
  Postoperative = "Postoperative",
  SpecificTimepoint = "SpecificTimepoint",
  Continuous = "Continuous",
  NotSpecified = "NotSpecified",
}

export enum TrialPhase {
  PhaseI = "PhaseI",
  PhaseII = "PhaseII",
  PhaseIII = "PhaseIII",
  PhaseIV = "PhaseIV",
  PostMarketing = "PostMarketing",
  NotSpecified = "NotSpecified",
}

export enum UrbanRural {
  Urban = "Urban",
  Rural = "Rural",
  NotSpecified = "NotSpecified",
}

/**
 * Retrieved article information
 */
export interface Article {
  /**
   * PubMed ID
   */
  pmid: string
  /**
   * Article title
   */
  title: string
  /**
   * Authors
   */
  authors: string
  /**
   * Journal citation
   */
  journal: string
  /**
   * Publication date
   */
  pub_date: string
  /**
   * Abstract text
   */
  abstract: string
  /**
   * DOI
   */
  doi?: string | null
  /**
   * Study design
   */
  study_design?: string | null
  /**
   * Sample size
   */
  sample_size?: number | null
  /**
   * Key findings
   */
  key_findings: string[]
  /**
   * Relevance score
   */
  relevance_score?: number | null
  
}

export interface ComparisonCriteria {
  comparison_type?: ComparisonType | null
  comparison_specificity?: ComparisonSpecificity | null
  specific_comparator: string[]
  comparison_dose_type?: ComparisonDoseType | null
  requires_dose_matching?: boolean | null
  same_administration_route?: boolean | null
  same_treatment_duration?: boolean | null
  requires_washout_period?: boolean | null
  randomized_sequence?: boolean | null
  
}

export interface Criterion {
  type: CriteriaType
  dimension: string
  description: string
  rationale?: string | null
  
}

export interface DataQualityCriteria {
  requires_sample_size?: boolean | null
  requires_mean_sd?: boolean | null
  requires_event_counts?: boolean | null
  requires_effect_size_ci?: boolean | null
  allows_figure_extraction?: boolean | null
  allows_missing_data?: boolean | null
  contact_author_for_data?: boolean | null
  requires_data_consistency?: boolean | null
  extraction_method: string[]
  required_data_format: DataFormat[]
  allows_data_conversion?: boolean | null
  timepoint_selection?: string | null
  requires_change_scores?: boolean | null
  
}

/**
 * Publication date range
 */
export interface DateRange {
  from_date?: string | null
  to_date?: string | null
  last_x_days?: number | null
  last_x_months?: number | null
  last_x_years?: number | null
  
}

/**
 * Effect size information
 */
export interface EffectSize {
  /**
   * Effect size type (e.g., MD, SMD, RR, OR)
   */
  type: string
  /**
   * Effect size value
   */
  value: number
  /**
   * Confidence interval lower bound
   */
  ci_lower: number
  /**
   * Confidence interval upper bound
   */
  ci_upper: number
  /**
   * P-value
   */
  p_value?: number | null
  /**
   * Outcome measure
   */
  outcome: string
  
}

export interface EthicsComplianceCriteria {
  requires_ethical_approval?: boolean | null
  requires_informed_consent?: boolean | null
  requires_trial_registration?: boolean | null
  funding_source?: FundingSource | null
  conflict_of_interest?: ConflictOfInterest | null
  compliance_standard: ComplianceStandard[]
  
}

export interface InclusionExclusionCriteria {
  study_design?: StudyDesignCriteria | null
  population?: PopulationCriteria | null
  intervention?: InterventionCriteria | null
  comparison?: ComparisonCriteria | null
  outcomes?: OutcomeCriteria | null
  publication?: PublicationCriteria | null
  data_quality?: DataQualityCriteria | null
  methodological_quality?: MethodologicalQualityCriteria | null
  setting?: SettingCriteria | null
  ethics_compliance?: EthicsComplianceCriteria | null
  additional_criteria: Criterion[]
  
}

export interface InterventionCriteria {
  intervention_category?: InterventionCategory | null
  specific_intervention: string[]
  allows_same_class_different_drug?: boolean | null
  administration_route: AdministrationRoute[]
  treatment_frequency?: TreatmentFrequency | null
  specific_frequency?: string | null
  treatment_timing?: TreatmentTiming | null
  dose_type?: DoseType | null
  specific_dose?: string | null
  dose_range?: string | null
  excludes_extreme_doses?: boolean | null
  requires_loading_dose?: boolean | null
  max_dose?: string | null
  min_treatment_duration_weeks?: number | null
  single_course_only?: boolean | null
  allows_multiple_courses?: boolean | null
  early_intervention?: boolean | null
  allows_repeated_treatment?: boolean | null
  provider_type: string[]
  implementation_setting: string[]
  combination_intervention?: CombinationIntervention | null
  allows_standard_background_therapy?: boolean | null
  allows_concomitant_therapy?: boolean | null
  requires_concomitant_reported?: boolean | null
  exposure_type?: ExposureType | null
  exposure_intensity?: ExposureIntensity | null
  exposure_duration?: ExposureDuration | null
  exposure_measurement?: string | null
  
}

/**
 * Journal-specific filters
 */
export interface JournalFilters {
  /**
   * Specific journal names
   */
  journal_names: string[]
  /**
   * Journal categories
   */
  journal_categories: string[]
  /**
   * Subset filters
   */
  subsets: string[]
  
}

/**
 * MeSH term with options
 */
export interface MeSHTerm {
  mesh_descriptor: string
  qualifiers: string[]
  explode: boolean
  major_topic: boolean
  
}

/**
 * Research question for meta-analysis
 */
export interface MetaAnalysisQuestion {
  /**
   * The research question
   */
  question: string
  /**
   * Context and background
   */
  context?: string | null
  /**
   * Population
   */
  population: string
  /**
   * Intervention
   */
  intervention: string
  /**
   * Comparison
   */
  comparison: string
  /**
   * Outcome
   */
  outcome: string
  
}

/**
 * Meta-analysis results
 */
export interface MetaAnalysisResult {
  /**
   * Research question
   */
  research_question: string
  /**
   * Search strategy used
   */
  search_strategy: string
  /**
   * Total articles found
   */
  total_found: number
  /**
   * Articles included after screening
   */
  articles_included: number
  /**
   * Extracted studies
   */
  studies: StudyExtraction[]
  /**
   * Synthesis findings
   */
  synthesis: string
  /**
   * Pooled effect size (if applicable)
   */
  pooled_effect?: EffectSize | null
  /**
   * Heterogeneity measure
   */
  heterogeneity?: string | null
  /**
   * Publication bias assessment
   */
  publication_bias?: string | null
  /**
   * Limitations
   */
  limitations: string[]
  /**
   * Conclusions
   */
  conclusions: string
  /**
   * Recommendations
   */
  recommendations: string[]
  
}

export interface MethodologicalQualityCriteria {
  bias_risk_level?: BiasRiskLevel | null
  bias_assessment_tool?: BiasAssessmentTool | null
  min_quality_score?: number | null
  min_low_risk_domains?: number | null
  requires_low_selection_bias?: boolean | null
  requires_low_performance_bias?: boolean | null
  requires_low_detection_bias?: boolean | null
  requires_low_attrition_bias?: boolean | null
  requires_complete_reporting?: boolean | null
  statistical_analysis?: StatisticalAnalysis | null
  requires_adjusted_effects?: boolean | null
  requires_intention_to_treat?: boolean | null
  requires_ethical_approval?: boolean | null
  requires_informed_consent?: boolean | null
  
}

export interface OutcomeCriteria {
  outcome_category?: OutcomeCategory | null
  outcome_nature: OutcomeNature[]
  outcome_data_type?: OutcomeDataType | null
  required_outcomes: string[]
  at_least_one_outcome: string[]
  excluded_outcomes: string[]
  excludes_surrogate_endpoints?: boolean | null
  measurement_method?: MeasurementMethod | null
  specific_scale: string[]
  requires_validated_tool?: boolean | null
  requires_blinded_assessment?: boolean | null
  requires_independent_assessment?: boolean | null
  self_reported?: boolean | null
  requires_mean_sd?: boolean | null
  requires_event_counts?: boolean | null
  requires_effect_size_ci?: boolean | null
  allows_data_extraction?: boolean | null
  follow_up_time?: FollowUpTime | null
  requires_adverse_events?: boolean | null
  requires_serious_adverse_events?: boolean | null
  adverse_event_definition?: string | null
  minimum_adverse_event_grade?: string | null
  
}

export interface PICO {
  population: string
  intervention: string
  comparison: string
  outcome: string
  
}

/**
 * PICO-based search strategy for systematic reviews
 */
export interface PICOSearchStrategy {
  /**
   * Population concept (P in PICO)
   */
  population: SearchConcept[]
  /**
   * Intervention concept (I in PICO)
   */
  intervention: SearchConcept[]
  /**
   * Comparison concept (C in PICO)
   */
  comparison: SearchConcept[]
  /**
   * Outcome concept (O in PICO)
   */
  outcome: SearchConcept[]
  /**
   * Study design filters
   */
  study_design: SearchConcept[]
  /**
   * Additional search blocks
   */
  additional_blocks: SearchBlock[]
  /**
   * Publication filters
   */
  publication_filters: PublicationFilters
  
}

export interface PopulationCriteria {
  age_group?: AgeGroup | null
  min_age?: number | null
  max_age?: number | null
  gender_requirement?: GenderRequirement | null
  min_female_percentage?: number | null
  disease_diagnosis?: string | null
  disease_subtype?: string | null
  disease_severity?: string | null
  disease_stage?: string | null
  diagnostic_criteria?: string | null
  requires_pathological_diagnosis?: boolean | null
  disease_activity?: DiseaseActivity | null
  disease_course?: DiseaseCourse | null
  baseline_condition?: string | null
  requires_comorbidities?: boolean | null
  allowed_comorbidities: string[]
  excluded_comorbidities: string[]
  treatment_history?: TreatmentHistory | null
  special_population?: SpecialPopulation | null
  analyze_special_population_separately?: boolean | null
  geographic_region: string[]
  medical_setting?: MedicalSetting | null
  income_level: string[]
  
}

export interface PublicationCriteria {
  publication_type?: PublicationType | null
  peer_review_status?: PeerReviewStatus | null
  grey_literature?: GreyLiterature | null
  requires_trial_registration?: boolean | null
  publication_language?: PublicationLanguage | null
  specific_languages: string[]
  min_publication_year?: number | null
  max_publication_year?: number | null
  within_last_x_years?: number | null
  journal_type: string[]
  min_impact_factor?: number | null
  specific_journals: string[]
  open_access_only?: boolean | null
  duplicate_publication_policy?: string | null
  
}

/**
 * Publication-related filters
 */
export interface PublicationFilters {
  /**
   * Date range filter
   */
  date_range?: DateRange | null
  /**
   * Article types to include
   */
  article_types: ArticleType[]
  /**
   * Species filter
   */
  species: Species[]
  /**
   * Sex filter
   */
  sex: Sex[]
  /**
   * Age groups
   */
  age_groups: PubMedAgeGroup[]
  /**
   * Languages
   */
  languages: Language[]
  /**
   * Journal filters
   */
  journal_filters?: JournalFilters | null
  
}

/**
 * Query refinement suggestion
 */
export interface QueryRefinement {
  /**
   * Original query
   */
  original_query: string
  /**
   * Refined query
   */
  refined_query: string
  /**
   * Changes made
   */
  changes: string[]
  /**
   * Reasoning
   */
  reasoning: string
  /**
   * Expected improvement
   */
  expected_improvement: string
  
}

/**
 * Rendered search query for a specific database
 */
export interface RenderedQuery {
  /**
   * Database this query is for
   */
  database: Database
  /**
   * Rendered query string
   */
  query: string
  /**
   * Query syntax used
   */
  syntax: string
  /**
   * Estimated results
   */
  estimated_results?: number | null
  
}

/**
 * Screening decision
 */
export interface ScreeningDecision {
  /**
   * PMID
   */
  pmid: string
  /**
   * Include or exclude
   */
  include: boolean
  /**
   * Reason for decision
   */
  reason: string
  /**
   * Relevance score
   */
  relevance_score?: number | null
  
}

/**
 * A search block combining concepts with a logical operator
 */
export interface SearchBlock {
  operator: LogicalOperator
  concepts: SearchConcept[]
  
}

/**
 * A search concept that combines multiple terms with OR logic
 */
export interface SearchConcept {
  name: string
  terms: SearchTerm[]
  required: boolean
  
}

/**
 * Search configuration for literature retrieval
 */
export interface SearchConfig {
  /**
   * Maximum number of articles to retrieve
   */
  max_articles: number
  /**
   * Date range for search
   */
  date_range: SearchDateRange
  /**
   * Study types to include
   */
  study_types: string[]
  /**
   * Language filter
   */
  languages: string[]
  /**
   * Minimum sample size
   */
  min_sample_size?: number | null
  
}

/**
 * Date range for publication filter
 */
export interface SearchDateRange {
  /**
   * Start date (YYYY-MM-DD)
   */
  from_date?: string | null
  /**
   * End date (YYYY-MM-DD)
   */
  to_date?: string | null
  /**
   * Last N years
   */
  last_n_years?: number | null
  
}

/**
 * Search options
 */
export interface SearchOptions {
  /**
   * Use automatic term mapping
   */
  automatic_term_mapping: boolean
  /**
   * Include PubMed Central
   */
  include_pmc: boolean
  /**
   * Use related articles
   */
  use_related_articles: boolean
  /**
   * Max results per database
   */
  max_results?: number | null
  
}

/**
 * Search result evaluation
 */
export interface SearchResultEvaluation {
  /**
   * Total articles found
   */
  total_found: number
  /**
   * Relevant articles count
   */
  relevant_count: number
  /**
   * Average relevance score
   */
  avg_relevance: number
  /**
   * Quality assessment
   */
  quality: string
  /**
   * Issues identified
   */
  issues: string[]
  /**
   * Recommendations
   */
  recommendations: string[]
  /**
   * Needs refinement
   */
  needs_refinement: boolean
  
}

/**
 * Complete search strategy for systematic review
 */
export interface SearchStrategy {
  /**
   * PICO-based search strategy
   */
  pico_strategy: PICOSearchStrategy
  /**
   * Strategy name/description
   */
  name: string
  /**
   * Description of the research question
   */
  description: string
  /**
   * Databases to search
   */
  databases: Database[]
  /**
   * Search options
   */
  options?: SearchOptions | null
  
}

/**
 * A single search term with field constraints
 */
export interface SearchTerm {
  term: string
  fields: PubMedField[]
  explode?: boolean | null
  use_reusable?: boolean | null
  
}

export interface SettingCriteria {
  hospital_level?: HospitalLevel | null
  specific_countries: string[]
  specific_regions: string[]
  study_scale?: StudyScale | null
  healthcare_system: string[]
  country_income_level?: CountryIncomeLevel | null
  urban_rural?: UrbanRural | null
  medical_resource_level?: string | null
  
}

/**
 * Evaluation of search strategy performance
 */
export interface StrategyEvaluation {
  /**
   * Number of results found
   */
  result_count: number
  /**
   * Precision (relevant results / total results)
   */
  precision?: number | null
  /**
   * Recall (relevant results found / total relevant results)
   */
  recall?: number | null
  /**
   * Suggestions for improvement
   */
  suggestions: string[]
  /**
   * Missing terms
   */
  missing_terms: string[]
  
}

export interface StudyDesignCriteria {
  study_design_type?: StudyDesignType | null
  rct_design_type?: RCTDesignType | null
  observational_study_type?: ObservationalStudyType | null
  min_total_sample_size?: number | null
  min_sample_size_per_group?: number | null
  min_event_count?: number | null
  requires_sample_size_calculation?: boolean | null
  min_statistical_power?: number | null
  randomization_method?: RandomizationMethod | null
  allocation_concealment?: AllocationConcealment | null
  blinding_type?: BlindingType | null
  outcome_assessor_blinding?: OutcomeAssessorBlinding | null
  follow_up_duration?: FollowUpDuration | null
  min_follow_up_weeks?: number | null
  max_loss_to_follow_up?: number | null
  requires_specific_timepoints?: boolean | null
  requires_final_followup?: boolean | null
  trial_phase?: TrialPhase | null
  study_nature?: StudyNature | null
  
}

/**
 * Study extraction results
 */
export interface StudyExtraction {
  /**
   * Article information
   */
  article: Article
  /**
   * Study population
   */
  population: string
  /**
   * Intervention details
   */
  intervention: string
  /**
   * Comparison details
   */
  comparison: string
  /**
   * Primary outcomes
   */
  primary_outcomes: string[]
  /**
   * Secondary outcomes
   */
  secondary_outcomes: string[]
  /**
   * Results summary
   */
  results_summary: string
  /**
   * Effect size data
   */
  effect_size?: EffectSize | null
  /**
   * Risk of bias assessment
   */
  risk_of_bias?: string | null
  /**
   * Quality score
   */
  quality_score?: number | null
  
}
