/**
 * Virtual File System Tools
 *
 * Tools for LLM to interact with S3-compatible storage (rustfs)
 */

import { z } from 'zod';

/**
 * Read file tool parameters
 */
export const readFileParams = z.object({
    path: z.string().describe('File path to read (e.g., "folder/file.json")'),
});

/**
 * Write file tool parameters
 */
export const writeFileParams = z.object({
    path: z.string().describe('File path to write (e.g., "folder/file.json")'),
    content: z.string().describe('Content to write to file'),
    contentType: z.string().optional().describe('Content type (e.g., "application/json", "text/markdown")'),
});

/**
 * List files tool parameters
 */
export const listFilesParams = z.object({
    path: z.string().optional().describe('Directory path to list (e.g., "folder/")'),
});

/**
 * Delete file tool parameters
 */
export const deleteFileParams = z.object({
    path: z.string().describe('File path to delete'),
});

/**
 * Export workspace tool parameters
 * The content is typically generated by the LLM based on workspace state
 * For auto-export, the content is generated by exportHandler in ExpertConfig
 */
export const exportWorkspaceParams = z.object({
    bucket: z.string().describe('Target bucket name'),
    path: z.string().describe('Destination path (e.g., "exports/report.json")'),
    content: z.string().describe('Content to export (typically rendered from workspace state)'),
    contentType: z.string().optional().describe('Content type (e.g., "application/json", "text/markdown")'),
});
