export {
  register,
  emailsSentCounter,
  inboxQueriesCounter,
  websocketConnectionsGauge,
  websocketConnectionDurationHistogram,
  requestDurationHistogram,
  errorCounter,
  messageOperationCounter,
  searchQueriesCounter,
  addressRegistrationCounter,
  websocketMessagesCounter,
  extractDomain,
  recordEmailSent,
  recordInboxQuery,
  recordWebSocketConnected,
  recordWebSocketDisconnected,
  recordError,
  recordMessageOperation,
  recordSearchQuery,
  recordAddressRegistration,
  recordWebSocketMessage,
  getMetrics,
  getMetricsContentType,
} from './metrics.js';
