#!/usr/bin/env python3
# spark-in 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# See https://documentation.dnanexus.com/developer for documentation and
# tutorials on how to modify this file.
#
# DNAnexus Python Bindings (dxpy) documentation:
#   http://autodoc.dnanexus.com/bindings/python/current/

import os
from time import sleep
import dxpy
import dxdata


@dxpy.entry_point("main")
def main():

    # Fill in your application code here.

    # The following line fills in some basic dummy output and assumes
    # that you have created variables to represent your output with
    # the same name as your output fields.

    output = {}

    # Initialize dxdata engine
    engine = dxdata.connect(dialect="hive+pyspark")

    return output


dxpy.run()
