services:
  redis:
    image: redis:trixie
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis_logs:/logs
    #配置文件启动
    command: redis-server /usr/local/etc/redis/redis.conf

  # Master database (for final merged data)
  db-master:
    image: pgvector/pgvector:pg16-trixie
    restart: always
    environment:
      POSTGRES_PASSWORD: fl5ox03
      POSTGRES_USER: admin
      POSTGRES_DB: biblib
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - main-network

  spark-iceberg:
    image: tabulario/spark-iceberg
    container_name: spark-iceberg
    networks:
      - main-network:
    depends_on:
      - rest
      - rustfs
    volumes:
      - ./warehouse:/home/iceberg/warehouse
      - ./notebooks:/home/iceberg/notebooks/notebooks
    environment:
      - AWS_ACCESS_KEY_ID=te5kyYAi155ZNJ681oxj
      - AWS_SECRET_ACCESS_KEY=ZrfqNqCHzwubj8J6JngsG8zUwNt3p7iTuoDUdn8P
      - AWS_REGION=us-east-1
    ports:
      - 8888:8888
      - 8080:8080
      - 10000:10000
      - 10001:10001
  rest:
    image: apache/iceberg-rest-fixture
    container_name: iceberg-rest
    networks:
      - main-network
    ports:
      - 8181:8181
    environment:
      - AWS_ACCESS_KEY_ID=te5kyYAi155ZNJ681oxj
      - AWS_SECRET_ACCESS_KEY=ZrfqNqCHzwubj8J6JngsG8zUwNt3p7iTuoDUdn8P
      - AWS_REGION=us-east-1
      - CATALOG_WAREHOUSE=s3://warehouse/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://rustfs:9000

  rustfs:
    image: rustfs/rustfs:latest
    restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - rustfs_data:/data
      - rustfs_logs:/logs
    networks:
      - main-network

networks:
  main-network:
    driver: bridge

volumes:
  redis_data:
  redis_logs:
  postgres_data:
  rustfs_data:
  rustfs_logs:
  mineru_data:
