services:
  db:
    image: pgvector/pgvector:pg16-trixie # It's recommended to use a specific version
    restart: always
    environment:
      POSTGRES_PASSWORD: fl5ox03 # Required
      POSTGRES_USER: admin # Optional, defaults to 'postgres'
      POSTGRES_DB: database # Optional, defaults to 'postgres'
    ports:
      - "5432:5432" # Maps container port 5432 to host port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data in a named volume

  rustfs:
    image: rustfs/rustfs:latest
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - rustfs_data:/data
      - rustfs_logs:/logs

volumes:
  postgres_data:
  rustfs_data:
  rustfs_logs: