# Use the base Node.js image with correct version
FROM ubuntu:latest

# Install system dependencies
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    pipx \
    nodejs \
    npm \
    git \
    python3 \
    make \
    g++ \
    && npm install -g pnpm \
    && pipx install uv \
    && pipx ensurepath



# Copy the rest of the application
COPY . .

# Build the application
# RUN pnpm build

# Expose the application port
EXPOSE 3000

# Default command
CMD ["pnpm", "start:dev"]