# Use the base Node.js image with correct version
FROM ubuntu:latest
ENV UV_HTTP_TIMEOUT=10000

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
ARG NODE_VERSION=20
RUN apt update && apt install curl -y
# install nvm
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash

# set env
ENV NVM_DIR=/root/.nvm

# install node
RUN bash -c "source $NVM_DIR/nvm.sh && nvm install $NODE_VERSION"

# set ENTRYPOINT for reloading nvm-environment
ENTRYPOINT ["bash", "-c", "source $NVM_DIR/nvm.sh && exec \"$@\"", "--"]

# Install system dependencies
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    pipx \
    npm \
    git \
    python3 \
    make \
    g++ \
    python3-dev \
    wget \
    curl \
    && npm install -g pnpm tsx\
    && pipx install uv \
    && pipx ensurepath

# RUN uv pip install -U crawl4ai
# RUN uv run crawl4ai-setup

# Build the application
# RUN pnpm build

# Expose the application port
EXPOSE 3000
EXPOSE 8000

# Default command
CMD ["pnpm", "start:dev"]