polaris:
  persistence:
    type: relational-jdbc
    jdbc:
      connection-url: jdbc:postgresql://iceberg-catalog-db:5432/iceberg
      username: admin
      password: fl5ox03
  realm-context:
    require-header: false
    default-realm: POLARIS
