#!/bin/bash

start_ukb_mcp() {
    echo "Starting ukb-mcp server..."
    cd bio_info
    source .venv/bin/activate
    cd apps/ukb-mcp
    exec uv run --active fastapi dev
}

activate_venv(){
    source /mnt/disk1/project/project/aikb/bio_info/.venv/bin/activate
}

enter_repl(){
    set -a  
    source /mnt/disk1/project/project/aikb/bio_info/.venv/bin/activate
    source /mnt/disk1/project/project/aikb/.env
    cd /mnt/disk1/project/project/aikb/bio_info
    export PYTHONPATH="$(pwd)/libs/datalake/src:$(pwd)/libs/dx-client/src:$(pwd)/libs/gwas-client/src:$(pwd)/libs/mono-cell/src:$(pwd)/libs/pride-client/src:$(pwd)/libs/pwas/src:$(pwd)/libs/pymr/src:$(pwd)/libs/rediomics/src:$PYTHONPATH"
    uv run --active python -i -c "import datalake as dk"
}

case "$1" in
    ukb-mcp)
        start_ukb_mcp
        ;;
    jupyter)
        set -a  
        source /mnt/disk1/project/project/aikb/.env
        uv run --with jupyter jupyter lab
        ;;
    venv)
        activate_venv
        ;;
    env)
        set -a  
        source /mnt/disk1/project/project/aikb/.env
        ;;
    repl)
        enter_repl
        ;;
    *)
        echo "Usage: $0 <task>"
        echo ""
        echo "Available tasks:"
        echo "  ukb-mcp    Start UK Biobank MCP server"
        echo "  venv    Activate bio_info venv"
        ;;
esac
