version: '3.8'

services:
  pdf-splitting-worker:
    build: .
    container_name: pdf-splitting-worker
    environment:
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin123
      - RABBITMQ_VHOST=my_vhost
      - PDF_OSS_BUCKET_NAME=aikb-pdf
      - OSS_REGION=oss-cn-beijing
      - S3_ENDPOINT=aliyuncs.com
      - SYSTEM_LOG_LEVEL=INFO
      - WORKER_ID=pdf-splitting-worker-docker
    volumes:
      - ./logs:/app/logs
      - ./temp:/tmp/pdf-processing
    depends_on:
      - rabbitmq
    restart: unless-stopped
    networks:
      - pdf-processing-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - pdf-processing-network

  # Optional: MinIO for S3-compatible storage
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - pdf-processing-network

volumes:
  rabbitmq_data:
  minio_data:

networks:
  pdf-processing-network:
    driver: bridge