/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type {
  BamlRuntime,
  BamlCtxManager,
  ClientRegistry,
  Image,
  Audio,
  Pdf,
  Video,
} from '@boundaryml/baml';
import { toBamlError, HTTPRequest } from '@boundaryml/baml';
import type { Checked, Check } from './types';
import type * as types from './types';
import type {
  AgentDecision,
  AgentState,
  CriteriaScore,
  Decision,
  DocumentEvaluation,
  DocumentToRerank,
  Entity,
  EssayGrade,
  EssaySubmission,
  Explanation,
  GradingCriteria,
  GrammarCorrection,
  HyDE_query,
  HyDE_rewrite_query,
  KnowledgePoints,
  Knowledge_extraction_tool,
  Message,
  MutatedQuiz,
  Option,
  Quiz_retrieval_tool,
  Rawquiz_A,
  Related_documents,
  RelationshipSummary,
  RetrievedDocument,
  StepResponse,
  StructureAnalysis,
  Task,
  Textbook_semantic_search_tool,
  ToolCall,
  ToolDefinition,
  ToolList,
  ToolParameter,
  ToolResult,
  TranslationCorrection,
  VocabularySuggestion,
} from './types';
import type TypeBuilder from './type_builder';

type BamlCallOptions = {
  tb?: TypeBuilder;
  clientRegistry?: ClientRegistry;
  env?: Record<string, string | undefined>;
};

export class HttpRequest {
  constructor(
    private runtime: BamlRuntime,
    private ctxManager: BamlCtxManager,
  ) {}

  AgentDecideNextAction(
    user_query: string,
    conversation_history: types.Message[],
    available_tools: types.ToolDefinition[],
    current_context: string,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'AgentDecideNextAction',
        {
          user_query: user_query,
          conversation_history: conversation_history,
          available_tools: available_tools,
          current_context: current_context,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnnotateClass(
    quiz_content: string,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'AnnotateClass',
        {
          quiz_content: quiz_content,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  CorrectTranslation(
    original: string,
    translation: string,
    context: string,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'CorrectTranslation',
        {
          original: original,
          translation: translation,
          context: context,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  EvaluateDocumentSufficiency(
    quiz_content: string,
    documents: types.RetrievedDocument[],
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'EvaluateDocumentSufficiency',
        {
          quiz_content: quiz_content,
          documents: documents,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  ExecuteToolCall(
    tool_name: string,
    parameters: Record<string, types.ToolParameter>,
    tool_definitions: types.ToolDefinition[],
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'ExecuteToolCall',
        {
          tool_name: tool_name,
          parameters: parameters,
          tool_definitions: tool_definitions,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  ExtractMainEntity(
    chunk_text: string,
    entity_type: string[],
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'ExtractMainEntity',
        {
          chunk_text: chunk_text,
          entity_type: entity_type,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  Extract_related_documents(
    quiz_content: string,
    documents: string[],
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'Extract_related_documents',
        {
          quiz_content: quiz_content,
          documents: documents,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  FilterRelatedChunks(
    quiz_content: string,
    documents: types.RetrievedDocument[],
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'FilterRelatedChunks',
        {
          quiz_content: quiz_content,
          documents: documents,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  FinalizeAgentResponse(
    conversation_history: types.Message[],
    accumulated_information: string,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'FinalizeAgentResponse',
        {
          conversation_history: conversation_history,
          accumulated_information: accumulated_information,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GenerateAgentResponse(
    user_query: string,
    tool_results: types.ToolResult[],
    conversation_history: types.Message[],
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'GenerateAgentResponse',
        {
          user_query: user_query,
          tool_results: tool_results,
          conversation_history: conversation_history,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GenerateAnswer(
    history?: string[] | null,
    query: string,
    documents: types.RetrievedDocument[],
    language: string,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'GenerateAnswer',
        {
          history: history ?? null,
          query: query,
          documents: documents,
          language: language,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GenerateAntiMemorizationQuiz(
    origin_quiz: string,
    related_chunks: string[],
    similar_quizes: string[],
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'GenerateAntiMemorizationQuiz',
        {
          origin_quiz: origin_quiz,
          related_chunks: related_chunks,
          similar_quizes: similar_quizes,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GenerateExplanation(
    question: string,
    answer: string,
    options: string[],
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'GenerateExplanation',
        {
          question: question,
          answer: answer,
          options: options,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GenerateExplanationForAnalysis(
    quiz: string,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'GenerateExplanationForAnalysis',
        {
          quiz: quiz,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GenerateQuizQuery(
    questionType: string,
    question: string,
    options: string[],
    answer: string,
    explanation: string,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'GenerateQuizQuery',
        {
          questionType: questionType,
          question: question,
          options: options,
          answer: answer,
          explanation: explanation,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GenerateQuizVarient(
    origin_quiz: string,
    related_chunks: string[],
    similar_quizes: string[],
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'GenerateQuizVarient',
        {
          origin_quiz: origin_quiz,
          related_chunks: related_chunks,
          similar_quizes: similar_quizes,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GenerateQuizzes_single(
    content: string,
    quiz_num: number,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'GenerateQuizzes_single',
        {
          content: content,
          quiz_num: quiz_num,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GetGradingCriteriaSet(
    criteria_type: string,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'GetGradingCriteriaSet',
        {
          criteria_type: criteria_type,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GradeEssayImage(
    essay: types.EssaySubmission,
    criteria: types.GradingCriteria[],
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'GradeEssayImage',
        {
          essay: essay,
          criteria: criteria,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GradeEssayText(
    essay: types.EssaySubmission,
    criteria: types.GradingCriteria[],
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'GradeEssayText',
        {
          essay: essay,
          criteria: criteria,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  HyDE_rewrite(
    query: string,
    language: string,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'HyDE_rewrite',
        {
          query: query,
          language: language,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  HyDE_rewriteForAnalysis(
    query: string,
    language: string,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'HyDE_rewriteForAnalysis',
        {
          query: query,
          language: language,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  PlanNextStep(
    user_query: string,
    tasks_avaliable: types.Task[],
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'PlanNextStep',
        {
          user_query: user_query,
          tasks_avaliable: tasks_avaliable,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  RerankDocuments(
    query: string,
    documents: types.DocumentToRerank[],
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'RerankDocuments',
        {
          query: query,
          documents: documents,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  SummarizeKnowledgePoint(
    quiz_content: string,
    quiz_explanation: string,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'SummarizeKnowledgePoint',
        {
          quiz_content: quiz_content,
          quiz_explanation: quiz_explanation,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  SummarizeKnowledgePointForAnalysis(
    quiz_content: string,
    quiz_explanation: string,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'SummarizeKnowledgePointForAnalysis',
        {
          quiz_content: quiz_content,
          quiz_explanation: quiz_explanation,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  SummarizeRelationships(
    quiz: string,
    knowledgePoints: string[],
    chunks: string[],
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'SummarizeRelationships',
        {
          quiz: quiz,
          knowledgePoints: knowledgePoints,
          chunks: chunks,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }
}

export class HttpStreamRequest {
  constructor(
    private runtime: BamlRuntime,
    private ctxManager: BamlCtxManager,
  ) {}

  AgentDecideNextAction(
    user_query: string,
    conversation_history: types.Message[],
    available_tools: types.ToolDefinition[],
    current_context: string,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'AgentDecideNextAction',
        {
          user_query: user_query,
          conversation_history: conversation_history,
          available_tools: available_tools,
          current_context: current_context,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnnotateClass(
    quiz_content: string,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'AnnotateClass',
        {
          quiz_content: quiz_content,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  CorrectTranslation(
    original: string,
    translation: string,
    context: string,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'CorrectTranslation',
        {
          original: original,
          translation: translation,
          context: context,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  EvaluateDocumentSufficiency(
    quiz_content: string,
    documents: types.RetrievedDocument[],
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'EvaluateDocumentSufficiency',
        {
          quiz_content: quiz_content,
          documents: documents,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  ExecuteToolCall(
    tool_name: string,
    parameters: Record<string, types.ToolParameter>,
    tool_definitions: types.ToolDefinition[],
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'ExecuteToolCall',
        {
          tool_name: tool_name,
          parameters: parameters,
          tool_definitions: tool_definitions,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  ExtractMainEntity(
    chunk_text: string,
    entity_type: string[],
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'ExtractMainEntity',
        {
          chunk_text: chunk_text,
          entity_type: entity_type,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  Extract_related_documents(
    quiz_content: string,
    documents: string[],
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'Extract_related_documents',
        {
          quiz_content: quiz_content,
          documents: documents,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  FilterRelatedChunks(
    quiz_content: string,
    documents: types.RetrievedDocument[],
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'FilterRelatedChunks',
        {
          quiz_content: quiz_content,
          documents: documents,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  FinalizeAgentResponse(
    conversation_history: types.Message[],
    accumulated_information: string,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'FinalizeAgentResponse',
        {
          conversation_history: conversation_history,
          accumulated_information: accumulated_information,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GenerateAgentResponse(
    user_query: string,
    tool_results: types.ToolResult[],
    conversation_history: types.Message[],
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'GenerateAgentResponse',
        {
          user_query: user_query,
          tool_results: tool_results,
          conversation_history: conversation_history,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GenerateAnswer(
    history?: string[] | null,
    query: string,
    documents: types.RetrievedDocument[],
    language: string,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'GenerateAnswer',
        {
          history: history ?? null,
          query: query,
          documents: documents,
          language: language,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GenerateAntiMemorizationQuiz(
    origin_quiz: string,
    related_chunks: string[],
    similar_quizes: string[],
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'GenerateAntiMemorizationQuiz',
        {
          origin_quiz: origin_quiz,
          related_chunks: related_chunks,
          similar_quizes: similar_quizes,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GenerateExplanation(
    question: string,
    answer: string,
    options: string[],
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'GenerateExplanation',
        {
          question: question,
          answer: answer,
          options: options,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GenerateExplanationForAnalysis(
    quiz: string,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'GenerateExplanationForAnalysis',
        {
          quiz: quiz,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GenerateQuizQuery(
    questionType: string,
    question: string,
    options: string[],
    answer: string,
    explanation: string,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'GenerateQuizQuery',
        {
          questionType: questionType,
          question: question,
          options: options,
          answer: answer,
          explanation: explanation,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GenerateQuizVarient(
    origin_quiz: string,
    related_chunks: string[],
    similar_quizes: string[],
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'GenerateQuizVarient',
        {
          origin_quiz: origin_quiz,
          related_chunks: related_chunks,
          similar_quizes: similar_quizes,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GenerateQuizzes_single(
    content: string,
    quiz_num: number,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'GenerateQuizzes_single',
        {
          content: content,
          quiz_num: quiz_num,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GetGradingCriteriaSet(
    criteria_type: string,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'GetGradingCriteriaSet',
        {
          criteria_type: criteria_type,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GradeEssayImage(
    essay: types.EssaySubmission,
    criteria: types.GradingCriteria[],
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'GradeEssayImage',
        {
          essay: essay,
          criteria: criteria,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  GradeEssayText(
    essay: types.EssaySubmission,
    criteria: types.GradingCriteria[],
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'GradeEssayText',
        {
          essay: essay,
          criteria: criteria,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  HyDE_rewrite(
    query: string,
    language: string,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'HyDE_rewrite',
        {
          query: query,
          language: language,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  HyDE_rewriteForAnalysis(
    query: string,
    language: string,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'HyDE_rewriteForAnalysis',
        {
          query: query,
          language: language,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  PlanNextStep(
    user_query: string,
    tasks_avaliable: types.Task[],
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'PlanNextStep',
        {
          user_query: user_query,
          tasks_avaliable: tasks_avaliable,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  RerankDocuments(
    query: string,
    documents: types.DocumentToRerank[],
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'RerankDocuments',
        {
          query: query,
          documents: documents,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  SummarizeKnowledgePoint(
    quiz_content: string,
    quiz_explanation: string,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'SummarizeKnowledgePoint',
        {
          quiz_content: quiz_content,
          quiz_explanation: quiz_explanation,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  SummarizeKnowledgePointForAnalysis(
    quiz_content: string,
    quiz_explanation: string,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'SummarizeKnowledgePointForAnalysis',
        {
          quiz_content: quiz_content,
          quiz_explanation: quiz_explanation,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  SummarizeRelationships(
    quiz: string,
    knowledgePoints: string[],
    chunks: string[],
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.buildRequestSync(
        'SummarizeRelationships',
        {
          quiz: quiz,
          knowledgePoints: knowledgePoints,
          chunks: chunks,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }
}
