/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export { FieldType, EnumBuilder, ClassBuilder }

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    AgentDecision: ClassViewer<'AgentDecision', "should_use_tool" | "selected_tool" | "reasoning" | "confidence">;
    
    AgentState: ClassViewer<'AgentState', "conversation_history" | "available_tools" | "current_context" | "step_count" | "max_steps">;
    
    CriteriaScore: ClassViewer<'CriteriaScore', "criteria_name" | "score" | "feedback" | "max_score">;
    
    Decision: ClassViewer<'Decision', "response" | "selected_task">;
    
    DocumentEvaluation: ClassViewer<'DocumentEvaluation', "sufficient" | "explanation" | "missed_knowledge_point">;
    
    DocumentToRerank: ClassViewer<'DocumentToRerank', "content" | "metadata">;
    
    Entity: ClassViewer<'Entity', "name" | "description" | "type">;
    
    EssayGrade: ClassViewer<'EssayGrade', "overall_score" | "criteria_scores" | "detailed_feedback" | "grammar_corrections" | "vocabulary_suggestions" | "structure_analysis" | "improvement_suggestions">;
    
    EssaySubmission: ClassViewer<'EssaySubmission', "essay_text" | "essay_image" | "question_prompt" | "grading_criteria" | "user_id" | "submission_time">;
    
    Explanation: ClassViewer<'Explanation', "explanation">;
    
    GradingCriteria: ClassViewer<'GradingCriteria', "name" | "description" | "weight">;
    
    GrammarCorrection: ClassViewer<'GrammarCorrection', "original_text" | "corrected_text" | "explanation" | "position_start" | "position_end">;
    
    HyDE_query: ClassViewer<'HyDE_query', "quesiont" | "HyDE_content">;
    
    HyDE_rewrite_query: ClassViewer<'HyDE_rewrite_query', "HyDE_answer">;
    
    KnowledgePoints: ClassViewer<'KnowledgePoints', "knowledgePoint" | "description">;
    
    Knowledge_extraction_tool: ClassViewer<'Knowledge_extraction_tool', "content" | "extract_type" | "format">;
    
    Message: ClassViewer<'Message', "role" | "content" | "timestamp" | "tool_calls" | "tool_results">;
    
    MutatedQuiz: ClassViewer<'MutatedQuiz', "question" | "options" | "answer" | "explanation">;
    
    Option: ClassViewer<'Option', "index" | "content">;
    
    Quiz_retrieval_tool: ClassViewer<'Quiz_retrieval_tool', "query" | "difficulty_level" | "subject" | "limit">;
    
    Rawquiz_A: ClassViewer<'Rawquiz_A', "question" | "options" | "answer">;
    
    Related_documents: ClassViewer<'Related_documents', "docIndex">;
    
    RelationshipSummary: ClassViewer<'RelationshipSummary', "summary">;
    
    RetrievedDocument: ClassViewer<'RetrievedDocument', "title" | "page_num" | "content" | "metadata">;
    
    StepResponse: ClassViewer<'StepResponse', "is_final_step" | "response" | "tool" | "reasoning">;
    
    StructureAnalysis: ClassViewer<'StructureAnalysis', "introduction_score" | "body_paragraphs_score" | "conclusion_score" | "coherence_score" | "transition_score">;
    
    Task: ClassViewer<'Task', "task_name" | "task_description" | "task_example_user_query">;
    
    Textbook_semantic_search_tool: ClassViewer<'Textbook_semantic_search_tool', "search_content" | "max_results" | "subject_filter">;
    
    ToolCall: ClassViewer<'ToolCall', "tool_name" | "parameters" | "id">;
    
    ToolDefinition: ClassViewer<'ToolDefinition', "name" | "description" | "parameters" | "required_parameters">;
    
    ToolList: ClassViewer<'ToolList', "tools">;
    
    ToolParameter: ClassViewer<'ToolParameter', "name" | "type" | "description" | "required">;
    
    ToolResult: ClassViewer<'ToolResult', "tool_id" | "result" | "success" | "error_message">;
    
    TranslationCorrection: ClassViewer<'TranslationCorrection', "score" | "correction" | "suggestions" | "grammar_teach" | "fullTrans">;
    
    VocabularySuggestion: ClassViewer<'VocabularySuggestion', "original_word" | "suggested_word" | "explanation" | "position_start" | "position_end">;
    
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "AgentDecision","AgentState","CriteriaScore","Decision","DocumentEvaluation","DocumentToRerank","Entity","EssayGrade","EssaySubmission","Explanation","GradingCriteria","GrammarCorrection","HyDE_query","HyDE_rewrite_query","KnowledgePoints","Knowledge_extraction_tool","Message","MutatedQuiz","Option","Quiz_retrieval_tool","Rawquiz_A","Related_documents","RelationshipSummary","RetrievedDocument","StepResponse","StructureAnalysis","Task","Textbook_semantic_search_tool","ToolCall","ToolDefinition","ToolList","ToolParameter","ToolResult","TranslationCorrection","VocabularySuggestion",
          ]),
          enums: new Set([
            
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.AgentDecision = this.tb.classViewer("AgentDecision", [
          "should_use_tool","selected_tool","reasoning","confidence",
        ]);
        
        this.AgentState = this.tb.classViewer("AgentState", [
          "conversation_history","available_tools","current_context","step_count","max_steps",
        ]);
        
        this.CriteriaScore = this.tb.classViewer("CriteriaScore", [
          "criteria_name","score","feedback","max_score",
        ]);
        
        this.Decision = this.tb.classViewer("Decision", [
          "response","selected_task",
        ]);
        
        this.DocumentEvaluation = this.tb.classViewer("DocumentEvaluation", [
          "sufficient","explanation","missed_knowledge_point",
        ]);
        
        this.DocumentToRerank = this.tb.classViewer("DocumentToRerank", [
          "content","metadata",
        ]);
        
        this.Entity = this.tb.classViewer("Entity", [
          "name","description","type",
        ]);
        
        this.EssayGrade = this.tb.classViewer("EssayGrade", [
          "overall_score","criteria_scores","detailed_feedback","grammar_corrections","vocabulary_suggestions","structure_analysis","improvement_suggestions",
        ]);
        
        this.EssaySubmission = this.tb.classViewer("EssaySubmission", [
          "essay_text","essay_image","question_prompt","grading_criteria","user_id","submission_time",
        ]);
        
        this.Explanation = this.tb.classViewer("Explanation", [
          "explanation",
        ]);
        
        this.GradingCriteria = this.tb.classViewer("GradingCriteria", [
          "name","description","weight",
        ]);
        
        this.GrammarCorrection = this.tb.classViewer("GrammarCorrection", [
          "original_text","corrected_text","explanation","position_start","position_end",
        ]);
        
        this.HyDE_query = this.tb.classViewer("HyDE_query", [
          "quesiont","HyDE_content",
        ]);
        
        this.HyDE_rewrite_query = this.tb.classViewer("HyDE_rewrite_query", [
          "HyDE_answer",
        ]);
        
        this.KnowledgePoints = this.tb.classViewer("KnowledgePoints", [
          "knowledgePoint","description",
        ]);
        
        this.Knowledge_extraction_tool = this.tb.classViewer("Knowledge_extraction_tool", [
          "content","extract_type","format",
        ]);
        
        this.Message = this.tb.classViewer("Message", [
          "role","content","timestamp","tool_calls","tool_results",
        ]);
        
        this.MutatedQuiz = this.tb.classViewer("MutatedQuiz", [
          "question","options","answer","explanation",
        ]);
        
        this.Option = this.tb.classViewer("Option", [
          "index","content",
        ]);
        
        this.Quiz_retrieval_tool = this.tb.classViewer("Quiz_retrieval_tool", [
          "query","difficulty_level","subject","limit",
        ]);
        
        this.Rawquiz_A = this.tb.classViewer("Rawquiz_A", [
          "question","options","answer",
        ]);
        
        this.Related_documents = this.tb.classViewer("Related_documents", [
          "docIndex",
        ]);
        
        this.RelationshipSummary = this.tb.classViewer("RelationshipSummary", [
          "summary",
        ]);
        
        this.RetrievedDocument = this.tb.classViewer("RetrievedDocument", [
          "title","page_num","content","metadata",
        ]);
        
        this.StepResponse = this.tb.classViewer("StepResponse", [
          "is_final_step","response","tool","reasoning",
        ]);
        
        this.StructureAnalysis = this.tb.classViewer("StructureAnalysis", [
          "introduction_score","body_paragraphs_score","conclusion_score","coherence_score","transition_score",
        ]);
        
        this.Task = this.tb.classViewer("Task", [
          "task_name","task_description","task_example_user_query",
        ]);
        
        this.Textbook_semantic_search_tool = this.tb.classViewer("Textbook_semantic_search_tool", [
          "search_content","max_results","subject_filter",
        ]);
        
        this.ToolCall = this.tb.classViewer("ToolCall", [
          "tool_name","parameters","id",
        ]);
        
        this.ToolDefinition = this.tb.classViewer("ToolDefinition", [
          "name","description","parameters","required_parameters",
        ]);
        
        this.ToolList = this.tb.classViewer("ToolList", [
          "tools",
        ]);
        
        this.ToolParameter = this.tb.classViewer("ToolParameter", [
          "name","type","description","required",
        ]);
        
        this.ToolResult = this.tb.classViewer("ToolResult", [
          "tool_id","result","success","error_message",
        ]);
        
        this.TranslationCorrection = this.tb.classViewer("TranslationCorrection", [
          "score","correction","suggestions","grammar_teach","fullTrans",
        ]);
        
        this.VocabularySuggestion = this.tb.classViewer("VocabularySuggestion", [
          "original_word","suggested_word","explanation","position_start","position_end",
        ]);
        
        
    }

    reset(): void {
        this.tb.reset();
        // TODO: This should happen in Rust. Problem is, when we construct the
        // typebuilder we instantiate class builders once and it seems to make
        // a JS copy, bypassing the Rust side? In Python however, every time we
        // access a class builder with @property, we get a new instance that
        // wraps over the Rust type builder, so we only need to call tb.reset().
        // In JS it's not possible unless we refactor the way class builders are
        // accessed.
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}