/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

const fileMap = {
  
  "clients.baml": "// Learn more about clients at https://docs.boundaryml.com/docs/snippets/clients/overview\n\nclient<llm> GLM4Flash {\n  provider openai-generic\n  options {\n    model \"glm-4-flash\"\n    api_key env.GLM_API_KEY\n    base_url \"https://open.bigmodel.cn/api/paas/v4\"\n  }\n}\n\n",
  "generators.baml": "// This helps use auto generate libraries you can use in the language of\n// your choice. You can have multiple generators if you use multiple languages.\n// Just ensure that the output_dir is different for each generator.\ngenerator target {\n    // Valid values: \"python/pydantic\", \"typescript\", \"ruby/sorbet\", \"rest/openapi\"\n    output_type \"typescript\"\n\n    // Where the generated code will be saved (relative to baml_src/)\n    output_dir \"../\"\n\n    // The version of the BAML package you have installed (e.g. same version as your baml-py or @boundaryml/baml).\n    // The BAML VSCode extension version should also match this version.\n    version \"0.208.1\"\n\n    // Valid values: \"sync\", \"async\"\n    // This controls what `b.FunctionName()` will be (sync or async).\n    default_client_mode async\n}\n",
  "zh/research.baml": "function Research(arg:string) -> string {\n    client GLM4Flash\n    prompt #\"\n        Make a knowledge note about {{arg}}\n    \"#\n}\n\nclass Entity_Plain_Definition {\n    definition string\n}\n\nfunction Generate_plain_definition(entity_name:string, desc_information: string) -> Entity_Plain_Definition{\n    client GLM4Flash\n    prompt #\"\n        {{_.role('user')}}\n\n        请你根据你所具有的知识，为 **{{entity_name}}** 编写定义\n        1. 要求描述精准，鼓励通过增加描述文本篇幅来提高精确度，但仍需考量简洁度\n        2. 使用专业用语，减少主观偏差\n\n        当前关于 **{{entity_name}}** 的描述信息：\n        {{desc_information}}\n\n        {{ctx.output_format}}\n    \"#\n}\n\ntest TestName {\n  functions [Generate_plain_definition]\n  args {\n    entity_name #\"\n      高血压\n    \"#\n    desc_information #\"\n      类型: 疾病\n    \"#\n  }\n}\n",
}
export const getBamlFiles = () => {
    return fileMap;
}