/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { BamlRuntime, BamlCtxManager, Image, Audio, Pdf, Video, FunctionLog } from
"@boundaryml/baml"
import { toBamlError, HTTPRequest, ClientRegistry } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type * as types from "./types"
import type {ArticleResult, ClinicalImplications, Demographics, EffectMeasures, Intervention, Outcome, PICOExtraction, PaperMetadata, PaperSummary, Population, QualityAssessment, Resume, RiskOfBias, SearchResultEvaluation, SearchStrategy, SearchStrategyAdjustment, StatisticalResults, StudyDesign} from "./types"
import type TypeBuilder from "./type_builder"
import type * as events from "./events"

type TickReason = "Unknown";

type BamlCallOptions<EventsT = never> = {
tb?: TypeBuilder
clientRegistry?: ClientRegistry
client?: string
env?: Record<string, string | undefined>
  onTick?: (reason: TickReason, log: FunctionLog | null) => void
  events?: EventsT
  }

  export class AsyncHttpRequest {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  async AdjustSearchStrategy(
  disease: string,previous_term: string,previous_count: number,top_articles: types.ArticleResult[],current_filters: string[],current_sort: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "AdjustSearchStrategy",
      {
      "disease": disease,"previous_term": previous_term,"previous_count": previous_count,"top_articles": top_articles,"current_filters": current_filters,"current_sort": current_sort
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async AssessStudyQuality(
  content: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "AssessStudyQuality",
      {
      "content": content
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async EvaluateSearchResults(
  disease: string,current_term: string,result_count: number,top_articles: types.ArticleResult[],current_filters: string[],target_count_min: number,target_count_max: number,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "EvaluateSearchResults",
      {
      "disease": disease,"current_term": current_term,"result_count": result_count,"top_articles": top_articles,"current_filters": current_filters,"target_count_min": target_count_min,"target_count_max": target_count_max
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async ExtractPICO(
  content: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "ExtractPICO",
      {
      "content": content
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async ExtractResume(
  resume: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "ExtractResume",
      {
      "resume": resume
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async GenerateSearchStrategy(
  disease: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "GenerateSearchStrategy",
      {
      "disease": disease
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async SummarizeMedicalLiterature(
  content: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "SummarizeMedicalLiterature",
      {
      "content": content
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async SummarizeMultiplePapers(
  papers: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "SummarizeMultiplePapers",
      {
      "papers": papers
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
      }

      export class AsyncHttpStreamRequest {
      constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

      
      async AdjustSearchStrategy(
      disease: string,previous_term: string,previous_count: number,top_articles: types.ArticleResult[],current_filters: string[],current_sort: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "AdjustSearchStrategy",
          {
          "disease": disease,"previous_term": previous_term,"previous_count": previous_count,"top_articles": top_articles,"current_filters": current_filters,"current_sort": current_sort
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async AssessStudyQuality(
      content: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "AssessStudyQuality",
          {
          "content": content
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async EvaluateSearchResults(
      disease: string,current_term: string,result_count: number,top_articles: types.ArticleResult[],current_filters: string[],target_count_min: number,target_count_max: number,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "EvaluateSearchResults",
          {
          "disease": disease,"current_term": current_term,"result_count": result_count,"top_articles": top_articles,"current_filters": current_filters,"target_count_min": target_count_min,"target_count_max": target_count_max
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async ExtractPICO(
      content: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "ExtractPICO",
          {
          "content": content
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async ExtractResume(
      resume: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "ExtractResume",
          {
          "resume": resume
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async GenerateSearchStrategy(
      disease: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "GenerateSearchStrategy",
          {
          "disease": disease
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async SummarizeMedicalLiterature(
      content: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "SummarizeMedicalLiterature",
          {
          "content": content
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async SummarizeMultiplePapers(
      papers: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "SummarizeMultiplePapers",
          {
          "papers": papers
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
          }