// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v3.21.12
// source: pdf2md.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "pdf2md";

/** PDF Chunk information */
export interface PdfChunk {
  chunkIndex: number;
  startPage: number;
  endPage: number;
  s3Key: string;
  fileName: string;
}

/** Request to convert PDF to Markdown */
export interface Pdf2MarkdownRequest {
  itemId: string;
  fileType: string;
  fileSize: number;
  fileHash: string;
  addDate: string;
  s3Key: string;
  pageCount: number;
  wordCount?: number | undefined;
}

/** Response from PDF to Markdown conversion */
export interface Pdf2MarkdownResponse {
  itemId: string;
  pageNum: number;
  chunked: boolean;
  chunkCount?: number | undefined;
  chunkSize?: number | undefined;
  markdownContent: string;
  chunks: PdfChunk[];
}

export const PDF2MD_PACKAGE_NAME = "pdf2md";

/** PDF2MD service definition */

export interface Pdf2MdServiceClient {
  /** Convert PDF to Markdown */

  convertPdfToMarkdown(request: Pdf2MarkdownRequest): Observable<Pdf2MarkdownResponse>;
}

/** PDF2MD service definition */

export interface Pdf2MdServiceController {
  /** Convert PDF to Markdown */

  convertPdfToMarkdown(
    request: Pdf2MarkdownRequest,
  ): Promise<Pdf2MarkdownResponse> | Observable<Pdf2MarkdownResponse> | Pdf2MarkdownResponse;
}

export function Pdf2MdServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["convertPdfToMarkdown"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("Pdf2MdService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("Pdf2MdService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PDF2_MD_SERVICE_NAME = "Pdf2MdService";
